In [7]:
import pandas as pd
import numpy as np
import pickle
dataset=pd.read_csv('sih2020data.csv')
print(dataset)

         Location  Age  Gender  Bacteria  Level  Year  Detected_Cases
0     Maharashtra   20    Male         1      1  2016            5000
1     Maharashtra   20    Male         1      2  2016            7000
2     Maharashtra   20    Male         1      3  2016            7000
3     Maharashtra   20    Male         1      4  2016            2000
4     Maharashtra   20    Male         1      1  2017            5000
5     Maharashtra   20    Male         1      2  2017            7000
6     Maharashtra   20    Male         1      3  2017            7000
7     Maharashtra   20    Male         1      4  2017            2000
8     Maharashtra   20    Male         1      1  2018            5000
9     Maharashtra   20    Male         1      2  2018            7000
10    Maharashtra   20    Male         1      3  2018            7000
11    Maharashtra   20    Male         1      4  2018            2000
12    Maharashtra   20    Male         1      1  2019            7000
13    Maharashtra   

In [8]:
#################general first case###########

from sklearn import linear_model
General1=linear_model.LinearRegression()
General1.fit(dataset[['Bacteria','Level','Year']],dataset.Detected_Cases)


def General(Bacteria,year):
    x=[]
    for level in range (1,5):       
        x.append(reg5.predict([(Bacteria,level,year)])[0])
    return x    


In [9]:
result=General(1,2021)
print(result)

NameError: name 'reg5' is not defined

In [11]:
filename = 'General1.sav'
pickle.dump(General1, open(filename, 'wb'))

In [12]:
Location1=linear_model.LinearRegression()
location=dataset['Location']=="Maharashtra"

dataset_filtered=dataset[location]

Location1.fit(dataset_filtered[['Bacteria','Level','Year']],dataset_filtered.Detected_Cases)
def Location1Fun(Bacteria,year):
    x=[]
    for level in range (1,5):       
        x.append(Location1.predict([(Bacteria,level,year)])[0])
    return x    
    
    
        

In [13]:
filename = 'Location1.sav'
pickle.dump(Location1, open(filename, 'wb'))

In [14]:
result=Location1Fun(1,2021)
print(result)

[32052.857142856345, 27712.857142856345, 23372.857142856345, 19032.857142856345]


In [15]:
Location2=linear_model.LinearRegression()
location=dataset['Location']=="Karnataka"
dataset_filtered=dataset[location]

Location2.fit(dataset_filtered[['Bacteria','Level','Year']],dataset_filtered.Detected_Cases)
def Location2Fun(Bacteria,year):
    x=[]
    for level in range (1,5):       
        x.append(Location2.predict([(Bacteria,level,year)])[0])
    return x   


In [16]:
result=Location2Fun(1,2021)
print(result)

[37052.857142856345, 32712.857142856345, 28372.857142856345, 24032.857142856345]


In [17]:
filename = 'Location2.sav'
pickle.dump(Location2, open(filename, 'wb'))

In [18]:
Location3=linear_model.LinearRegression()
location=dataset['Location']=="Gujarat"
dataset_filtered=dataset[location]
print(dataset_filtered)
Location3.fit(dataset_filtered[['Bacteria','Level','Year']],dataset_filtered.Detected_Cases)
def Location3Fun(Bacteria,year):
    x=[]
    for level in range (1,5):       
        x.append(Location3.predict([(Bacteria,level,year)])[0])
    return x   


     Location  Age  Gender  Bacteria  Level  Year  Detected_Cases
5040  Gujarat   20    Male         1      1  2016           12000
5041  Gujarat   20    Male         1      2  2016           14000
5042  Gujarat   20    Male         1      3  2016           14000
5043  Gujarat   20    Male         1      4  2016            9000
5044  Gujarat   20    Male         1      1  2017           12000
5045  Gujarat   20    Male         1      2  2017           14000
5046  Gujarat   20    Male         1      3  2017           14000
5047  Gujarat   20    Male         1      4  2017            9000
5048  Gujarat   20    Male         1      1  2018           12000
5049  Gujarat   20    Male         1      2  2018           14000
5050  Gujarat   20    Male         1      3  2018           14000
5051  Gujarat   20    Male         1      4  2018            9000
5052  Gujarat   20    Male         1      1  2019           14000
5053  Gujarat   20    Male         1      2  2019           15000
5054  Guja

In [19]:
result=Location3Fun(1,2021)
print(result)

[39052.857142856345, 34712.857142856345, 30372.857142856345, 26032.857142856345]


In [20]:
filename = 'Location3.sav'
pickle.dump(Location3, open(filename, 'wb'))

In [91]:
Age=linear_model.LinearRegression()
print(dataset)
Age.fit(dataset[['Age','Bacteria','Level','Year']],dataset.Detected_Cases)

Age.predict([(40,1,1,2020)])

         Location  Age  Gender  Bacteria  Level  Year  Detected_Cases
0     Maharashtra   20       1         1      1  2016            5000
1     Maharashtra   20       1         1      2  2016            7000
2     Maharashtra   20       1         1      3  2016            7000
3     Maharashtra   20       1         1      4  2016            2000
4     Maharashtra   20       1         1      1  2017            5000
5     Maharashtra   20       1         1      2  2017            7000
6     Maharashtra   20       1         1      3  2017            7000
7     Maharashtra   20       1         1      4  2017            2000
8     Maharashtra   20       1         1      1  2018            5000
9     Maharashtra   20       1         1      2  2018            7000
10    Maharashtra   20       1         1      3  2018            7000
11    Maharashtra   20       1         1      4  2018            2000
12    Maharashtra   20       1         1      1  2019            7000
13    Maharashtra   

array([31888.29013947])

In [22]:
filename = 'Age.sav'
pickle.dump(Age, open(filename, 'wb'))

In [79]:
Gender=linear_model.LinearRegression()
dataset['Gender']= le.fit_transform(dataset['Gender']) 
Gender.fit(dataset[['Gender','Bacteria','Level','Year']],dataset.Detected_Cases)
print(dataset)
Gender.predict([(1,1,1,2020)])

         Location  Age  Gender  Bacteria  Level  Year  Detected_Cases
0     Maharashtra   20       1         1      1  2016            5000
1     Maharashtra   20       1         1      2  2016            7000
2     Maharashtra   20       1         1      3  2016            7000
3     Maharashtra   20       1         1      4  2016            2000
4     Maharashtra   20       1         1      1  2017            5000
5     Maharashtra   20       1         1      2  2017            7000
6     Maharashtra   20       1         1      3  2017            7000
7     Maharashtra   20       1         1      4  2017            2000
8     Maharashtra   20       1         1      1  2018            5000
9     Maharashtra   20       1         1      2  2018            7000
10    Maharashtra   20       1         1      3  2018            7000
11    Maharashtra   20       1         1      4  2018            2000
12    Maharashtra   20       1         1      1  2019            7000
13    Maharashtra   

array([32102.85714286])

In [24]:
filename = 'Gender.sav'
pickle.dump(Gender, open(filename, 'wb'))

In [25]:
Charts=linear_model.LinearRegression()
print(dataset)
Charts.fit(dataset[['Bacteria','Level','Year']],dataset.Detected_Cases)
l1=[]
l2=[]
l3=[]
l4=[]
Charts.predict([(1,1,2020)])

def chartsInLevels(Bacteria,startYear,endYear):
    for years in range(startYear,endYear):
        for levels in range (1,5):
        
            if(levels==1):
                l1.append(int(Charts.predict([(Bacteria,levels,years)])[0]))
            elif(levels==2):
                l2.append(int(Charts.predict([(Bacteria,levels,years)])[0]))
            elif(levels==3):
                l3.append(int(Charts.predict([(Bacteria,levels,years)])[0])) 
            else:
                l4.append(int(Charts.predict([(Bacteria,levels,years)])[0])) 
            
            
            
print(l1)
print(l2)
print(l3)
print(l4)

         Location  Age  Gender  Bacteria  Level  Year  Detected_Cases
0     Maharashtra   20    Male         1      1  2016            5000
1     Maharashtra   20    Male         1      2  2016            7000
2     Maharashtra   20    Male         1      3  2016            7000
3     Maharashtra   20    Male         1      4  2016            2000
4     Maharashtra   20    Male         1      1  2017            5000
5     Maharashtra   20    Male         1      2  2017            7000
6     Maharashtra   20    Male         1      3  2017            7000
7     Maharashtra   20    Male         1      4  2017            2000
8     Maharashtra   20    Male         1      1  2018            5000
9     Maharashtra   20    Male         1      2  2018            7000
10    Maharashtra   20    Male         1      3  2018            7000
11    Maharashtra   20    Male         1      4  2018            2000
12    Maharashtra   20    Male         1      1  2019            7000
13    Maharashtra   

In [26]:
chartsInLevels(1,2020,2030)
            
print(l1)
print(l2)
print(l3)
print(l4)

[31102, 36052, 41002, 45952, 50902, 55852, 60802, 65752, 70702, 75652]
[26762, 31712, 36662, 41612, 46562, 51512, 56462, 61412, 66362, 71312]
[22422, 27372, 32322, 37272, 42222, 47172, 52122, 57072, 62022, 66972]
[18082, 23032, 27982, 32932, 37882, 42832, 47782, 52732, 57682, 62632]


In [27]:
filename = 'Charts.sav'
pickle.dump(Charts, open(filename, 'wb'))

In [75]:
datasetEf=pd.read_csv('sih2020dEfficiencyata.csv')
print(datasetEf)

   Antibiotics  Year  Efficiency
0        ABBL1  2014        0.90
1        ABBL2  2014        0.80
2        ABBL3  2014        0.95
3        ABBL4  2014        0.97
4        ABBL1  2015        0.85
5        ABBL2  2015        0.70
6        ABBL3  2015        0.93
7        ABBL4  2015        0.95
8        ABBL1  2016        0.75
9        ABBL2  2016        0.65
10       ABBL3  2016        0.90
11       ABBL4  2016        0.95
12       ABBL1  2017        0.65
13       ABBL2  2017        0.55
14       ABBL3  2017        0.87
15       ABBL4  2017        0.93
16       ABBL1  2018        0.55
17       ABBL2  2018        0.45
18       ABBL3  2018        0.85
19       ABBL4  2018        0.91
20       ABBL1  2019        0.45
21       ABBL2  2019        0.45
22       ABBL3  2019        0.82
23       ABBL4  2019        0.88
24       ABBL1  2020        0.35
25       ABBL2  2020        0.45
26       ABBL3  2020        0.80
27       ABBL4  2020        0.85


In [76]:
Efficiency=linear_model.LinearRegression()


In [77]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
##dataset_filtered1=datasetEf[anti]
##print(dataset_filtered1)
datasetEf['Antibiotics']= le.fit_transform(datasetEf['Antibiotics']) 

Efficiency.fit(datasetEf[['Antibiotics','Year']],datasetEf.Efficiency)
Efficiency.predict([(0,2025)])

array([0.18057143])

In [78]:
filename = 'Efficiency.sav'
pickle.dump(Efficiency, open(filename, 'wb'))

In [178]:
location=dataset['Location']==""
dataset_filtered=dataset[location]
print(dataset_filtered)

Empty DataFrame
Columns: [Location, Age , Gender, Bacteria, Level, Year, Detected_Cases]
Index: []


In [83]:
from sklearn import linear_model
reg5=linear_model.LinearRegression()
from sklearn.preprocessing import LabelEncoder 
  
le = LabelEncoder() 
  
dataset_filtered['Location']= le.fit_transform(dataset_filtered['Location']) 
dataset_filtered['Level']= le.fit_transform(dataset_filtered['Level']) 
print(dataset_filtered.head())
x=dataset_filtered[['Location','Level','Year']]

print(x)
reg5.fit(x,dataset_filtered.Detected_Cases)
(reg5.predict([(0,5,2018)]))



    

KeyError: 'Location'

In [90]:
x=[]
for anti in range(0,4):
    
    x.append(Efficiency.predict([(anti,2030)])[0])

print (x)    

[-0.07210714285713493, 0.040607142857155054, 0.15332142857143083, 0.2660357142857208]


In [52]:
X = dataset_filtered[['Year']]
# y.shape should be (N, 1)
y =dataset_filtered['label'] 
# perform label encoding if "label" contains strings
# y = pd.factorize(mydata['label'])[0].reshape(-1, 1) 
X_train, X_test, y_train, y_test = train_test_split(
                      X, y, test_size=0.33, random_state=42)
...

clf.fit(X_train, y_train) 
print(clf.score(X_test, y_test))

KeyError: 'label'